[package]
name = "ckb-bls"
version = "0.0.1"
authors = [""]
edition = "2018"
build = "build.rs"
license = "MIT"
description = ""
repository = "https://github.com/AlphaCryp/trusteeship"
include = ["src/**/*", "Cargo.toml", "build.rs", "specs/cells/*"]

[dependencies]
includedir = "0.5.0"
phf = "0.7.21"

[build-dependencies]
includedir_codegen = "0.5.0"
blake2b-rs = "0.1.5"
faster-hex = "0.3"

[dev-dependencies]
byteorder = "1.3.1"
ckb-types = { git = "https://github.com/nervosnetwork/ckb.git", rev = "d75e4c5" }
ckb-script = { git = "https://github.com/nervosnetwork/ckb.git", rev = "d75e4c5" }
ckb-dao-utils = { git = "https://github.com/nervosnetwork/ckb.git", rev = "d75e4c5" }
ckb-hash = { git = "https://github.com/nervosnetwork/ckb.git", rev = "d75e4c5" }
ckb-error = { git = "https://github.com/nervosnetwork/ckb.git", rev = "d75e4c5" }
rand = "0.6.5"
lazy_static = "1.3.0"
ripemd160 = "0.8.0"
sha2 = "0.8.0"
faster-hex = "0.3"
bls = { path = "bls" }
